[phases.setup]
nixPkgs = ["nodejs_20", "git", "python3", "gnumake", "gcc"]

[phases.install]
cmds = [
  "git config --global url.'https://'.insteadOf git://",
  "npm install --legacy-peer-deps"
]

[start]
cmd = "node src/index.js"
